### ISSUE TITLE
Use translatable="false" instead of translatable="true"

### ISSUE THREAD

**Issue by Dennis123789** [creativetrendsapps/folio#14]
`translatable="true"` means it CAN be translated, while `translatable="false"` mean you can't.

**Comment by creativetrendsapps** [comment]
I am aware of this. As I am using Eclipse and not Android Studio Eclipse doesn't like the fact that is there. Android lint isn't following my command to ignore such things, so I've just left it to make my life easier. I've closed the original issue for this reason, as this isn't high on my list of corrections and fixes.

**Comment by creativetrendsapps** [comment]
I'm converting Folio to gradle today so this shouldn't be an issue any longer.
