### ISSUE TITLE
Use translatable="false" for non-translatable strings

### ISSUE THREAD

**Issue by Dennis123789** [creativetrendsapps/folio#5]
Consider using translatable="false" for non-translatable Strings. Strings like the app-name, names of persons in credits and the licenses should not be translated. Use this attribute so they will be left out of translations and translators will know they don't have to translate it.

More info: https://sites.google.com/a/android.com/tools/recent/non-translatablestrings

**Comment by creativetrendsapps** [comment]
Thanks. translatable="false" was originally placed in the strings. As I use Eclipse I got tired of the error that it was throwing and just replaced it. I will however switch it back.
